export const DISCOVERY = {
  SERPER_DELAY_MS: Number(process.env.SERPER_DELAY_MS ?? 250),
  WAYBACK_DELAY_MS: Number(process.env.WAYBACK_DELAY_MS ?? 1000),
  PAGE_CONCURRENCY: Number(process.env.DISCOVERY_PAGE_CONCURRENCY ?? 2),
  CLAUDE_MODEL: process.env.CLAUDE_MODEL ?? 'claude-sonnet-4-5-20250929',
  MAX_SERPER_QUERIES_PER_LEAD: Number(process.env.MAX_SERPER_QUERIES_PER_LEAD ?? 8),
  MAX_LINKEDIN_PROFILES_PER_LEAD: Number(process.env.MAX_LINKEDIN_PROFILES_PER_LEAD ?? 3),
  MAX_CLAUDE_CALLS_PER_LEAD: Number(process.env.MAX_CLAUDE_CALLS_PER_LEAD ?? 1),
  CONTACT_SYNC_THRESHOLD: Number(process.env.CONTACT_SYNC_THRESHOLD ?? 20),
  CANDIDATE_THRESHOLD: Number(process.env.CANDIDATE_THRESHOLD ?? 10),
};
